/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sat Dec  1 16:01:40 2018. */

#ifndef PB_TELEMETRY_PB_H_INCLUDED
#define PB_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Telemetry {
    bool movement;
    int32_t luminosity;
/* @@protoc_insertion_point(struct:Telemetry) */
} Telemetry;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Telemetry_init_default                   {0, 0}
#define Telemetry_init_zero                      {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Telemetry_movement_tag                   1
#define Telemetry_luminosity_tag                 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Telemetry_fields[3];

/* Maximum encoded size of messages (where known) */
#define Telemetry_size                           13

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TELEMETRY_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
