/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sat Dec  1 16:01:40 2018. */

#include "telemetry.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Telemetry_fields[3] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, Telemetry, movement, movement, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, Telemetry, luminosity, movement, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
